# Generated by Django 5.2.8 on 2025-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appt_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow-up', 'Follow-Up'), ('physical', 'Physical'), ('telehealth', 'Telehealth')], max_length=32)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
